name: my_anime
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dio: ^5.2.1
  flutter_spinkit: ^5.2.0
  youtube_player_flutter: ^8.1.2
  flutter_screenutil: ^5.8.4
  url_launcher: ^6.1.12
  path_provider: ^2.0.15
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

